main.exe : Main.o Actions.o AssetManager.o Asteroids.o Bird.o Collision.o Explosion.o Falling_Asteroids.o Flash.o Game.o GameOverState.o GameState.o Gravity.o HUD.o InputManager.o Land.o MainMenuState.o Pipe.o set_of_gas.o SplashState.o StateMachine.o Wapen.o Bullet.o BulletArray.o
	g++ ".\Build\Main.o" ".\Build\Actions.o" ".\Build\AssetManager.o" ".\Build\Asteroids.o" ".\Build\Bird.o" ".\Build\Collision.o" ".\Build\Explosion.o" ".\Build\Falling_Asteroids.o" ".\Build\Flash.o" ".\Build\Game.o" ".\Build\GameOverState.o" ".\Build\GameState.o" ".\Build\Gravity.o" ".\Build\HUD.o" ".\Build\InputManager.o" ".\Build\Land.o" ".\Build\MainMenuState.o" ".\Build\Pipe.o" ".\Build\set_of_gas.o" ".\Build\SplashState.o" ".\Build\StateMachine.o" ".\Build\Wapen.o" ".\Build\Bullet.o" ".\Build\BulletArray.o" -o ".\Build\main.exe" -LC:\SFML-2.5.1\lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio
	".\Build\main.exe"

Main.o: main.cpp
	g++ -c main.cpp -IC:\SFML-2.5.1\include -o ".\Build\Main.o"

Actions.o: Actions.cpp Actions.hpp
	g++ -c Actions.cpp -IC:\SFML-2.5.1\include -o ".\Build\Actions.o"

AssetManager.o: AssetManager.cpp AssetManager.hpp
	g++ -c AssetManager.cpp -IC:\SFML-2.5.1\include -o ".\Build\AssetManager.o"

Asteroids.o: Asteroids.cpp Asteroids.hpp
	g++ -c Asteroids.cpp -IC:\SFML-2.5.1\include -o ".\Build\Asteroids.o"

Bird.o: Bird.cpp Bird.hpp
	g++ -c Bird.cpp -IC:\SFML-2.5.1\include -o ".\Build\Bird.o"

Collision.o: Collision.cpp Collision.hpp
	g++ -c Collision.cpp -IC:\SFML-2.5.1\include -o ".\Build\Collision.o"

Explosion.o: Explosion.cpp Explosion.hpp
	g++ -c Explosion.cpp -IC:\SFML-2.5.1\include -o ".\Build\Explosion.o"

Falling_Asteroids.o: Falling_Asteroids.cpp Falling_Asteroids.hpp
	g++ -c Falling_Asteroids.cpp -IC:\SFML-2.5.1\include -o ".\Build\Falling_Asteroids.o"

Flash.o: Flash.cpp Flash.hpp
	g++ -c Flash.cpp -IC:\SFML-2.5.1\include -o ".\Build\Flash.o"

Game.o: Game.cpp Game.hpp
	g++ -c Game.cpp -IC:\SFML-2.5.1\include -o ".\Build\Game.o"

GameOverState.o: GameOverState.cpp GameOverState.hpp
	g++ -c GameOverState.cpp -IC:\SFML-2.5.1\include -o ".\Build\GameOverState.o"

GameState.o: GameState.cpp GameState.hpp
	g++ -c GameState.cpp -IC:\SFML-2.5.1\include -o ".\Build\GameState.o"

Gravity.o: Gravity.cpp Gravity.hpp
	g++ -c Gravity.cpp -IC:\SFML-2.5.1\include -o ".\Build\Gravity.o"

HUD.o: HUD.cpp HUD.hpp
	g++ -c HUD.cpp -IC:\SFML-2.5.1\include -o ".\Build\HUD.o"

InputManager.o: InputManager.cpp InputManager.hpp
	g++ -c InputManager.cpp -IC:\SFML-2.5.1\include -o ".\Build\InputManager.o"

Land.o: Land.cpp Land.hpp
	g++ -c Land.cpp -IC:\SFML-2.5.1\include -o ".\Build\Land.o"

MainMenuState.o: MainMenuState.cpp MainMenuState.hpp
	g++ -c MainMenuState.cpp -IC:\SFML-2.5.1\include -o ".\Build\MainMenuState.o"

Pipe.o: Pipe.cpp Pipe.hpp
	g++ -c Pipe.cpp -IC:\SFML-2.5.1\include -o ".\Build\Pipe.o"

set_of_gas.o: set_of_gas.cpp set_of_gas.hpp
	g++ -c set_of_gas.cpp -IC:\SFML-2.5.1\include -o ".\Build\set_of_gas.o"

SplashState.o: SplashState.cpp SplashState.hpp
	g++ -c SplashState.cpp -IC:\SFML-2.5.1\include -o ".\Build\SplashState.o"

StateMachine.o: StateMachine.cpp StateMachine.hpp
	g++ -c StateMachine.cpp -IC:\SFML-2.5.1\include -o ".\Build\StateMachine.o"

Wapen.o: Wapen.cpp Wapen.hpp
	g++ -c Wapen.cpp -IC:\SFML-2.5.1\include -o ".\Build\Wapen.o"

Bullet.o: Bullet.cpp Bullet.hpp
	g++ -c Bullet.cpp -IC:\SFML-2.5.1\include -o ".\Build\Bullet.o"

BulletArray.o: BulletArray.cpp BulletArray.hpp
	g++ -c BulletArray.cpp -IC:\SFML-2.5.1\include -o ".\Build\BulletArray.o"